# Generated by Django 2.2 on 2021-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ManyToManyField(to='home.Country'),
        ),
    ]
