# Generated by Django 2.2 on 2021-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210215_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='comapny',
            field=models.ManyToManyField(to='home.Company'),
        ),
    ]
