# Generated by Django 2.2 on 2021-02-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210216_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='comapny',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Country'),
        ),
    ]
