# Generated by Django 2.2 on 2021-02-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210216_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Country'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Objective'),
        ),
    ]
