# Generated by Django 2.2 on 2021-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210216_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
    ]
