# Generated by Django 2.2 on 2021-02-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210216_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Objective'),
        ),
    ]
